// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaOe8BzcT-d9OmiRXTHJVMB8noE9ZQmto',
    appId: '1:282540499079:web:6c84512867826103ba1822',
    messagingSenderId: '282540499079',
    projectId: 'matterportal',
    authDomain: 'matterportal.firebaseapp.com',
    storageBucket: 'matterportal.appspot.com',
    measurementId: 'G-0VT6BXFQNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh_2zEQ_ijoiZxqK3tEsRsJqoIHt3RGLM',
    appId: '1:282540499079:android:8731e33c07029e42ba1822',
    messagingSenderId: '282540499079',
    projectId: 'matterportal',
    storageBucket: 'matterportal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8igYkx-LkZLZraJ5Ekp8rdnKwnH2xLN4',
    appId: '1:282540499079:ios:7dd71d3e05e7c5d4ba1822',
    messagingSenderId: '282540499079',
    projectId: 'matterportal',
    storageBucket: 'matterportal.appspot.com',
    iosBundleId: 'cc.blackmatter.portal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8igYkx-LkZLZraJ5Ekp8rdnKwnH2xLN4',
    appId: '1:282540499079:ios:7dd71d3e05e7c5d4ba1822',
    messagingSenderId: '282540499079',
    projectId: 'matterportal',
    storageBucket: 'matterportal.appspot.com',
    iosBundleId: 'cc.blackmatter.portal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaOe8BzcT-d9OmiRXTHJVMB8noE9ZQmto',
    appId: '1:282540499079:web:6c84512867826103ba1822',
    messagingSenderId: '282540499079',
    projectId: 'matterportal',
    authDomain: 'matterportal.firebaseapp.com',
    storageBucket: 'matterportal.appspot.com',
    measurementId: 'G-0VT6BXFQNL',
  );
}
