class MetadataLanguage {
  final String code;
  final String name;

  const MetadataLanguage(this.code, this.name);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MetadataLanguage &&
          runtimeType == other.runtimeType &&
          code == other.code;

  @override
  int get hashCode => code.hashCode;

  @override
  String toString() => name;
}

const List<MetadataLanguage> metadataLanguages = [
  MetadataLanguage('en', 'English'),
  MetadataLanguage('ar', 'Arabic'),
  MetadataLanguage('zh', 'Chinese'),
  MetadataLanguage('fr', 'French'),
  MetadataLanguage('de', 'German'),
  MetadataLanguage('hi', 'Hindi'),
  MetadataLanguage('it', 'Italian'),
  MetadataLanguage('ja', 'Japanese'),
  MetadataLanguage('ko', 'Korean'),
  MetadataLanguage('pt', 'Portuguese'),
  MetadataLanguage('ru', 'Russian'),
  MetadataLanguage('es', 'Spanish'),
];
const List<String> genres = [
  'Alternative',
  'Anime',
  'Arabic',
  'Audiobooks',
  'Blues',
  'Brazilian',
  'Children\'s Music',
  'Chinese',
  'Christian & Gospel',
  'Classical',
  'Comedy',
  'Country',
  'Dance',
  'Disney',
  'Easy Listening',
  'Electronic',
  'Enka',
  'Fitness & Workout',
  'Folk',
  'French Pop',
  'Funk',
  'German Folk',
  'German Pop',
  'Heavy Metal',
  'Hip Hop/Rap',
  'Holiday',
  'Indian',
  'Inspirational',
  'Instrumental',
  'J-pop',
  'Jazz',
  'Karaoke',
  'Kayokyoku',
  'Korean',
  'Latin',
  'Marching Bands',
  'New Age',
  'Other',
  'Pop',
  'Punk',
  'R&B/Soul',
  'Reggae',
  'Rock',
  'Singer/Songwriter',
  'Soundtrack',
  'Spoken Word',
  'Vocal',
  'World'
];
const Map<String, List<String>> subgenres = {
  'Alternative': [
    'Chinese Alt',
    'College Rock',
    'EMO',
    'Goth Rock',
    'Grunge',
    'Indie Pop',
    'Indie Rock',
    'Korean Indie',
    'New Wave',
    'Pop Punk',
    'Punk'
  ],
  'Anime': [
    'Anime',
  ],
  'Arabic': ['Arabic Pop', 'Islamic', 'Khaleeji', 'North African'],
  'Audiobooks': ['Audiobooks'],
  'Blues': [
    'Acoustic Blues',
    'Blues',
    'Chicago Blues',
    'Classic Blues',
    'Contemporary Blues',
    'Country Blues',
    'Delta Blues',
    'Electric Blues',
    'Traditional Blues'
  ],
  'Brazilian': [
    'Axé',
    'Baile Funk',
    'Bossa Nova',
    'Brazilian',
    'Choro',
    'Forró',
    'Frevo',
    'MPB',
    'Pagode',
    'Samba',
    'Sertanejo'
  ],
  'Children\'s Music': [
    'Children\'s Music',
    'Lullabies',
    'Sing-Along',
    'Stories'
  ],
  'Chinese': [
    'Chinese',
    'Chinese Classical',
    'Chinese Flute',
    'Chinese Opera',
    'Chinese Orchestral',
    'Chinese Regional Folk',
    'Chinese Strings',
    'Taiwanese Folk',
    'Tibetan Native Music'
  ],
  'Christian & Gospel': [
    'CCM',
    'Christian & Gospel',
    'Christian Metal',
    'Christian Pop',
    'Christian Rap',
    'Christian Rock',
    'Classic Christian',
    'Contemporary Gospel',
    'Gospel',
    'Praise & Worship',
    'Southern Gospel',
    'Traditional Gospel'
  ],
  'Classical': [
    'Art Song',
    'Avant-Garde',
    'Baroque Era',
    'Brass & Woodwinds',
    'Cantata',
    'Cello',
    'Chamber Music',
    'Chant',
    'Choral',
    'Classical',
    'Classical Crossover',
    'Classical Era',
    'Contemporary Era',
    'Electronic',
    'Guitar',
    'Impressionist',
    'Medieval Era',
    'Minimalism',
    'Modern Era',
    'Opera',
    'Oratorio',
    'Orchestral',
    'Percussion',
    'Piano',
    'Renaissance',
    'Romantic Era',
    'Sacred',
    'Solo Instrumental',
    'Violin'
  ],
  'Comedy': ['Comedy', 'Novelty', 'Standup Comedy'],
  'Country': [
    'Alternative Country',
    'Americana',
    'Bluegrass',
    'Contemporary Bluegrass',
    'Contemporary Country',
    'Country',
    'Country Gospel',
    'Honky Tonk',
    'Outlaw Country',
    'Thai Country',
    'Traditional Bluegrass',
    'Traditional Country',
    'Urban Cowboy'
  ],
  'Dance': [
    'Afro House',
    'Amapiano',
    'Bass House',
    'Big Room',
    'Breakbeat',
    'Breaks',
    'Chill Out',
    'Classic House',
    'Dance',
    'Deep House',
    'DJ Tools',
    'Drum & Bass',
    'Dubstep',
    'Electro House',
    'Electronica',
    'Funky House',
    'Future House',
    'Glitch Hop',
    'Hard Dance',
    'Hard Techno',
    'Hardcore',
    'House',
    'Indie Dance',
    'Jackin\' House',
    'Jungle',
    'Minimal',
    'Nu Disco / Disco',
    'Progressive House',
    'Psy-Trance',
    'Soulful House',
    'Tech House'
  ],
  'Disney': [
    'Disney',
  ],
  'Easy Listening': ['Easy Listening', 'Lounge', 'Swing'],
  'Electronic': [
    '140 / Deep Dubstep',
    'Acapellas',
    'Acid House',
    'Afro / Latin',
    'Afro Pop',
    'Ambient',
    'Baile Funk',
    'Bass',
    'Bassline',
    'Battle Tools',
    'Bounce',
    'Breaks',
    'Broken Beat',
    'Broken Techno',
    'Chill Out',
    'Dark & Forest',
    'Dark Disco',
    'Deep / Hypnotic Techno',
    'Deep Drum & Bass',
    'Deep House',
    'Deep Tech',
    'Deep Trance',
    'DJ Tools',
    'Downtempo',
    'Driving Techno',
    'Drum & Bass',
    'Dub Techno',
    'Dubstep',
    'EBM Techno',
    'Electro',
    'Electro House',
    'Electro Pop',
    'Electronic',
    'Electronica',
    'Frenchcore',
    'Full-On',
    'Funk / Soul',
    'Future Bass',
    'Future Rave',
    'Glitch Hop',
    'Goa Trance',
    'Gqom',
    'Grime',
    'Halftime',
    'Happy Hardcore',
    'Hard Dance',
    'Hard House',
    'Hard Techno',
    'Hard Trance',
    'Hardstyle',
    'House',
    'Hypnotic Trance',
    'IDM/Experimental',
    'Indie Dance',
    'Industrial',
    'Italo',
    'Jump Up',
    'Latin Tech',
    'Liquid',
    'Loops',
    'Mainstage',
    'Melodic Dubstep',
    'Melodic House',
    'Melodic Techno',
    'Midtempo',
    'Minimal',
    'Neo Rave',
    'Organic House',
    'Peak Time Techno',
    'Phonk',
    'Pop',
    'Progressive House',
    'Progressive Psy',
    'Progressive Trance',
    'Psy-Trance',
    'Psychedelic',
    'Psycore & Hi-Tech',
    'Raw Techno',
    'Raw Trance',
    'Speed House',
    'Tech House',
    'Tech Trance',
    'Techno',
    'Terror',
    'Trance',
    'Trap',
    'Tropical House',
    'UK Bass',
    'Uplifting Trance',
    'Uptempo',
    'Vocal Trance',
    'Wave'
  ],
  'Enka': [
    'Enka',
  ],
  'Fitness & Workout': [
    'Fitness & Workout',
  ],
  'Folk': ['Contemporary Folk', 'Folk', 'Traditional Folk'],
  'French Pop': [
    'French Pop',
  ],
  'Funk': [
    'Funk',
  ],
  'German Folk': [
    'German Folk',
  ],
  'German Pop': [
    'German Pop',
  ],
  'Heavy Metal': [
    'Heavy Metal',
  ],
  'Hip Hop/Rap': [
    'Alternative Rap',
    'Chinese Hip-Hop',
    'Dirty South',
    'East Coast Rap',
    'Gangsta Rap',
    'Hardcore Rap',
    'Hip Hop/Rap',
    'Hip-Hop',
    'Korean Hip-Hop',
    'Latin Rap',
    'Old School Rap',
    'Rap',
    'UK Hip Hop',
    'Underground Rap',
    'West Coast Rap'
  ],
  'Holiday': [
    'Chanukah',
    'Christmas',
    'Christmas: Children\'s',
    'Christmas: Classic',
    'Christmas: Classical',
    'Christmas: Jazz',
    'Christmas: Modern',
    'Christmas: Pop',
    'Christmas: R&B',
    'Christmas: Religious',
    'Christmas: Rock',
    'Easter',
    'Halloween',
    'Holiday',
    'Thanksgiving'
  ],
  'Indian': [
    'Bollywood',
    'Devotional & Spiritual',
    'Ghazals',
    'Indian',
    'Indian Classical',
    'Indian Folk',
    'Indian Pop',
    'Regional Indian',
    'Sufi',
    'Tamil',
    'Telugu'
  ],
  'Inspirational': [
    'Inspirational',
  ],
  'Instrumental': [
    'Instrumental',
  ],
  'J-pop': [
    'J-pop',
  ],
  'Jazz': [
    'Acid Jazz',
    'Avant-Garde Jazz',
    'Bebop',
    'Big Band',
    'Contemporary Jazz',
    'Cool',
    'Crossover Jazz',
    'Dixieland',
    'Fusion',
    'Hard Bop',
    'Jazz',
    'Latin Jazz',
    'Mainstream Jazz',
    'Ragtime',
    'Smooth Jazz',
    'Traditional Jazz',
    'Vocal Jazz'
  ],
  'Karaoke': ['Instrumental', 'Karaoke'],
  'Kayokyoku': [
    'Kayokyoku',
  ],
  'Korean': ['Korean', 'Korean Traditional'],
  'Latin': [
    'Alternativo & Rock Latino',
    'Baladas y Boleros',
    'Contemporary Latin',
    'Latin',
    'Latin Jazz',
    'Pop Latino',
    'Raices',
    'Reggaeton',
    'Regional Mexicano',
    'Salsa y Tropical',
    'Urbano Latino'
  ],
  'Marching Bands': [
    'Marching Bands',
  ],
  'New Age': [
    'Healing',
    'Meditation',
    'Nature',
    'New age',
    'Relaxation',
    'Travel',
    'Yoga'
  ],
  'Other': [
    'Spoken Word',
  ],
  'Pop': [
    'Adult Contemporary',
    'Alternative Pop',
    'Britpop',
    'Cantopop',
    'Dance Pop',
    'Disco',
    'French Pop',
    'German Pop',
    'Indo Pop',
    'K-Pop',
    'Korean Folk-Pop',
    'Malaysian Pop',
    'Mandopop',
    'Manilla Sound',
    'New Wave',
    'Oldies',
    'Original Pilipino Music',
    'Pinoy Pop',
    'Pop',
    'Pop/Rock',
    'Soft Rock',
    'Tai-Pop',
    'Teen Pop',
    'Thai Pop'
  ],
  'Punk': [
    'Punk',
  ],
  'R&B/Soul': [
    'Contemporary R&B',
    'Disco',
    'Doo Wop',
    'Funk',
    'Motown',
    'Neo-Soul',
    'R&B/Soul',
    'Soul',
    'Soul/R&B'
  ],
  'Reggae': [
    'Dancehall/Reggae',
    'Dub',
    'Lovers Rock',
    'Modern Dancehall',
    'Pop-Reggae',
    'Ragga',
    'Reggae',
    'Roots Reggae',
    'Ska'
  ],
  'Rock': [
    'Adult Alternative',
    'American Trad Rock',
    'Arena Rock',
    'Blues-Rock',
    'British Invasion',
    'Chinese Rock',
    'Classic Rock',
    'Death Metal/Black Metal',
    'Glam Rock',
    'Hair Metal',
    'Hard Rock',
    'Heavy Metal',
    'Jam Bands',
    'Korean Rock',
    'Metal',
    'Prog-Rock/Art Rock',
    'Psychedelic',
    'Psychedelic Rock',
    'Rock',
    'Rock & Roll',
    'Rockabilly',
    'Roots Rock',
    'Southern Rock',
    'Surf',
    'Tex-Mex'
  ],
  'Singer/Songwriter': [
    'Alternative Folk',
    'Contemporary Folk',
    'Contemporary Singer/Songwriter',
    'Folk-Rock',
    'New Acoustic',
    'Singer/Songwriter',
    'Traditional Folk'
  ],
  'Soundtrack': [
    'Foreign Cinema',
    'Musicals',
    'Original Score',
    'Sound Effects',
    'Soundtrack',
    'TV Soundtrack',
    'Video Game'
  ],
  'Spoken Word': [
    'Spoken Word',
  ],
  'Vocal': ['Standards', 'Traditional Pop', 'Trot', 'Vocal', 'Vocal Pop'],
  'World': [
    'Africa',
    'Afrikaans',
    'Afro-Beat',
    'Afro-Pop',
    'Arabesque',
    'Asia',
    'Australia',
    'Cajun',
    'Calypso',
    'Caribbean',
    'Celtic',
    'Celtic Folk',
    'Contemporary Celtic',
    'Dangdut',
    'Dini',
    'Europe',
    'Fado',
    'Farsi',
    'Flamenco',
    'France',
    'Halk',
    'Hawaii',
    'Iberia',
    'Indonesian Religious',
    'Inspirational',
    'Israeli',
    'Japan',
    'Klezmer',
    'North America',
    'Polka',
    'Russian',
    'Russian Chanson',
    'Sanat',
    'Soca',
    'South Africa',
    'South America',
    'Tango',
    'Traditional Celtic',
    'Turkish',
    'World'
  ]
};
const List<String> productTypes = [
  'Single',
  'EP',
  'Album',
];
const List<String> prices = [
  'Single - Back',
  'Single - Mid',
  'Single - Front',
  'Album - Digital 45',
  'Album - Mini EP',
  'Album - EP',
  'Album - Mini Album Two',
  'Album - Mini Album One',
  'Album - Budget One',
  'Album - Budget Two',
  'Album - Back',
  'Album - Mid',
  'Album - Mid/Front',
  'Album - Front One',
  'Album - Front Two',
  'Album - Front/Plus',
  'Album - Deluxe One',
  'Album - Deluxe Two',
  'Album - Deluxe Three',
  'Album - Deluxe Four'
];
