// Performance roles
const List<String> performerRoles = [
  '12-String Guitar',
  'Accordion',
  'Acoustic Guitar',
  'Actor',
  'Alto Saxophone',
  'Alto Solo',
  'Anime Character',
  'Background Vocals',
  'Banjo',
  'Baritone Saxophone',
  'Baritone Solo',
  'Bass Clarinet',
  'Bass Guitar',
  'Bass Trombone',
  'Bassoon',
  'Bells',
  'Bongos',
  'Cajon',
  'Cello',
  'Choir',
  'Choir Master',
  'Chorus',
  'Clarinet',
  'Classical Guitar',
  'Clavier',
  'Conductor',
  'Congas',
  'Cornet',
  'Countertenor Solo',
  'DJ',
  'Djembe',
  'Double Bass',
  'Drums',
  'Electric Guitar',
  'Ensemble',
  'Fiddle',
  'First Violin',
  'Flugelhorn',
  'Flute',
  'Fretless Electric Bass Guitar',
  'Guitar',
  'Hammond Organ',
  'Harmonica',
  'Harmony Vocals',
  'Harp',
  'Harpsichord',
  'Horn',
  'Keyboards',
  'Kora',
  'Lead Guitar',
  'Lead Vocals',
  'Lute',
  'Mandolin',
  'Metallophone',
  'Mezzo-Soprano Solo',
  'Mixed Artist',
  'Music Director',
  'Oboe',
  'Orchestra',
  'Organ',
  'Pedal Steel Guitar',
  'Percussion',
  'Piano',
  'Piccolo',
  'Programming',
  'Rap',
  'Recorder',
  'Rhodes Piano',
  'Rhythm Guitar',
  'Sampled Artist',
  'Saxophone',
  'Second Violin',
  'Sitar',
  'Soprano Saxophone',
  'Soprano Solo',
  'Steel Guitar',
  'Synthesizer',
  'Tabla',
  'Tambourine',
  'Tenor Saxophone',
  'Tenor Solo',
  'Timbales',
  'Timpani',
  'Trombone',
  'Trumpet',
  'Tuba',
  'Ukulele',
  'Upright Bass',
  'Viola',
  'Viola de Gamba',
  'Violin',
  'Vocal Ensemble',
  'Vocal Solo',
  'Vocals',
  'Whistle',
  'Xylophone',
];

// Writing roles
const List<String> writerRoles = [
  'Adapter',
  'Arranger',
  'Composer',
  'Librettist',
  'Lyricist',
  'Songwriter',
  'Transcriber',
  'Vocal Adaptation',
];

// Production roles
const List<String> productionRoles = [
  'Assistant Engineer',
  'Co-Producer',
  'Graphic Design',
  'Guitar Technician',
  'Mastering Engineer',
  'Mixing Engineer',
  'Producer',
  'Production Assistant',
  'Recording Engineer',
  'Sound Engineer',
  'Vocal Engineer',
];
